# Travis CI configuration file
language: ruby

bundler_args: --without development

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2

gemfile:
  - Gemfile

services:
  - mongodb

install:
  - bundle install

env:

before_script:

script:
  - RAILS_ENV=test bundle exec rake test:units

branches:
  only:
    - develop/master
